/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empmgmt.gui;

import empmgmt.dbutil.DBconnection;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class OptainsFrame extends javax.swing.JFrame {

    /**
     * Creates new form OptainsFrame
     */
    public OptainsFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OptionChoice = new javax.swing.ButtonGroup();
        myPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        radAdd = new javax.swing.JRadioButton();
        radSearch = new javax.swing.JRadioButton();
        radDisplay = new javax.swing.JRadioButton();
        radUpdate = new javax.swing.JRadioButton();
        radDelete = new javax.swing.JRadioButton();
        btnCont = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        myPanel.setBackground(new java.awt.Color(0, 0, 0));
        myPanel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Employe Management Application");

        OptionChoice.add(radAdd);
        radAdd.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        radAdd.setForeground(new java.awt.Color(255, 255, 255));
        radAdd.setText("Add ");
        radAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAddActionPerformed(evt);
            }
        });

        OptionChoice.add(radSearch);
        radSearch.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        radSearch.setForeground(new java.awt.Color(255, 255, 255));
        radSearch.setText("Search ");

        OptionChoice.add(radDisplay);
        radDisplay.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        radDisplay.setForeground(new java.awt.Color(255, 255, 255));
        radDisplay.setText(" Display All");

        OptionChoice.add(radUpdate);
        radUpdate.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        radUpdate.setForeground(new java.awt.Color(255, 255, 255));
        radUpdate.setText("Update ");

        OptionChoice.add(radDelete);
        radDelete.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        radDelete.setForeground(new java.awt.Color(255, 255, 255));
        radDelete.setText("Delete");

        btnCont.setBackground(new java.awt.Color(153, 153, 153));
        btnCont.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCont.setForeground(new java.awt.Color(0, 51, 51));
        btnCont.setText("Continue");
        btnCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setText("<--  Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout myPanelLayout = new javax.swing.GroupLayout(myPanel);
        myPanel.setLayout(myPanelLayout);
        myPanelLayout.setHorizontalGroup(
            myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(myPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myPanelLayout.createSequentialGroup()
                        .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(radDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(148, 148, 148))
                    .addGroup(myPanelLayout.createSequentialGroup()
                        .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(radUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radDisplay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCont, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(88, 88, 88))
        );
        myPanelLayout.setVerticalGroup(
            myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myPanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnCont)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radAdd)
                        .addGap(18, 18, 18)
                        .addComponent(radDelete)
                        .addGap(18, 18, 18)
                        .addComponent(radSearch)
                        .addGap(18, 18, 18)))
                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myPanelLayout.createSequentialGroup()
                        .addComponent(radUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(radDisplay))
                    .addGroup(myPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnExit)))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    private void radAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAddActionPerformed
     
    }//GEN-LAST:event_radAddActionPerformed

    private void btnContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContActionPerformed
    if(!radAdd.isSelected() && !radDelete.isSelected() &&!radDisplay.isSelected()
                 &&!radSearch.isSelected() &&!radUpdate.isSelected()){
        JOptionPane.showMessageDialog(null,"Please Select an Option ","Error",JOptionPane.ERROR_MESSAGE);
        return;
    }
    if(radAdd.isSelected()){
      AddEmploye addEmp = new AddEmploye();
      addEmp.setVisible(true);
      this.dispose();
    }
    else if(radSearch.isSelected()){
      SearchEmploye searchEmp = new SearchEmploye();
      searchEmp.setVisible(true);
      this.dispose();
    }
    else if(radDisplay.isSelected()){
      DisplayAll disEmp = new DisplayAll();
      disEmp.setVisible(true);
      this.dispose();
    }
    else if(radDelete.isSelected()){
      DeleteRecord delEmp = new DeleteRecord();
      delEmp.setVisible(true);
      this.dispose();
    }
    else if(radUpdate.isSelected()){
      UpdateRecord updateEmp = new UpdateRecord();
      updateEmp.setVisible(true);
      this.dispose();
    }    
    }//GEN-LAST:event_btnContActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
    int cond = JOptionPane.showConfirmDialog(null,"Do you want to exit ?", "Exit",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
     if(cond==JOptionPane.YES_OPTION){
     DBconnection.closeConnection();
     System.exit(0);
     }
    }//GEN-LAST:event_btnExitActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptainsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptainsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptainsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptainsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptainsFrame().setVisible(true);
            }
        });
    }
    
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup OptionChoice;
    private javax.swing.JButton btnCont;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel myPanel;
    private javax.swing.JRadioButton radAdd;
    private javax.swing.JRadioButton radDelete;
    private javax.swing.JRadioButton radDisplay;
    private javax.swing.JRadioButton radSearch;
    private javax.swing.JRadioButton radUpdate;
    // End of variables declaration//GEN-END:variables
}
